name: percollate
base: core18 # the base snap is the execution environment for this snap
version: '1.0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Convert web pages to PDF, EPUB or HTML files
description: |
  Percollate is a command-line tool that turns web pages into beautifully formatted PDF, EPUB, or HTML files.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict

parts:
  application:
    # See 'snapcraft plugins'
    plugin: nodejs
    nodejs-version: 10.22.0
    nodejs-package-manager: npm
    source: https://github.com/danburzo/percollate.git
    source-tag: v1.0.1
    stage-packages:
      - ca-certificates
      - fonts-liberation
      - libappindicator3-1
      - libasound2
      - libatk-bridge2.0-0
      - libatk1.0-0
      - libcairo2
      - libcups2
      - libdbus-1-3
      - libexpat1
      - libfontconfig1
      - libgbm1
      - libgcc1
      - libglib2.0-0
      - libgtk-3-0
      - libnspr4
      - libnss3
      - libpango-1.0-0
      - libpangocairo-1.0-0
      - libx11-6
      - libx11-xcb1
      - libxcb1
      - libxcomposite1
      - libxcursor1
      - libxdamage1
      - libxext6
      - libxfixes3
      - libxi6
      - libxrandr2
      - libxrender1
      - libxss1
      - libxtst6
      - lsb-release
      - wget
      - xdg-utils

  cleanup:
    after: [application]
    plugin: nil
    build-snaps:
      - core18
      - gtk-common-themes
      - gnome-3-28-1804
    override-prime: |
      set -eux
      for snap in "core18" "gtk-common-themes" "gnome-3-28-1804"; do
        cd "/snap/$snap/current" && find . -type f,l -exec rm -r "$SNAPCRAFT_PRIME/{}" \;
      done

plugs:
  browser-sandbox:
    interface: browser-support
    allow-sandbox: true

apps:
  percollate:
    extensions: [gnome-3-28]
    command: percollate
    plugs: [home, network, browser-support]
